title: Blog
description: >- # this means to ignore newlines until "baseurl:"
  My blog. 
baseurl: ""
domain: blog.infected.lol
url: "https://blog.infected.lol"
github_username: sapphirevx 

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
